name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          # list of Docker images to use as base name for tags
          images: |
            kevac/node-mysql-exporter-s3
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
